// <auto-generated />
namespace claseMVCts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class precio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(precio));
        
        string IMigrationMetadata.Id
        {
            get { return "201503200254374_precio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
